var wordList = [
    "acne",
    "acre",
    "addendum",
    "advertise",
    "aircraft",
    "aisle",
    "alligator",
    "alphabetize",
    "america",
    "ankle",
    "apathy",
    "applause",
    "applesauce",
    "application",
    "archaeologist",
    "aristocrat",
    "arm",
    "asleep",
    "astronaut",
    "athlete",
    "atlantis",
    "aunt",
    "avocado",
    "baby-sitter",
    "backbone",
    "bag",
    "baguette",
    "bald",
    "balloon",
    "banana",
    "baseball",
    "basketball",
    "bat",
    "battery",
    "beach",
    "bedbug",
    "beer",
    "beethoven",
    "belt",
    "bib",
    "bicycle",
    "bike",
    "billboard",
    "bird",
    "birthday",
    "bite",
    "blanket",
    "bleach",
    "blossom",
    "blueprint",
    "blunt",
    "blur",
    "boa",
    "boat",
    "bobsled",
    "body",
    "bomb",
    "book",
    "booth",
    "bowtie",
    "box",
    "brainstorm",
    "brand",
    "brave",
    "bridge",
    "broccoli",
    "broken",
    "broom",
    "bruise",
    "bubble",
    "buddy",
    "buffalo",
    "bulb",
    "bunny",
    "bus",
    "buy",
    "cabin",
    "cafeteria",
    "cake",
    "calculator",
    "campsite",
    "can",
    "canada",
    "candle",
    "candy",
    "cape",
    "car",
    "cardboard",
    "cat",
    "cd",
    "ceiling",
    "cell",
    "century",
    "chair",
    "chalk",
    "champion",
    "charge",
    "cheerleader",
    "chef",
    "chess",
    "chew",
    "chicken",
    "chime",
    "china",
    "chocolate",
    "church",
    "circus",
    "clay",
    "cliff",
    "cloak",
    "clockwork",
    "clown",
    "clue",
    "coach",
    "coal",
    "coaster",
    "cog",
    "cold",
    "college",
    "comfort",
    "computer",
    "cone",
    "conversation",
    "cook",
    "coop",
    "cord",
    "corduroy",
    "cot",
    "cough",
    "cow",
    "cowboy",
    "crayon",
    "cream",
    "crisp",
    "criticize",
    "crow",
    "cruise",
    "crumb",
    "crust",
    "cuff",
    "curtain",
    "cuticle",
    "dad",
    "dart",
    "dawn",
    "day",
    "deep",
    "defect",
    "dent",
    "dentist",
    "desk",
    "dictionary",
    "dimple",
    "dirty",
    "dismantle",
    "ditch",
    "diver",
    "doctor",
    "dog",
    "doghouse",
    "doll",
    "dominoes",
    "door",
    "dot",
    "drain",
    "draw",
    "dream",
    "dress",
    "drink",
    "drip",
    "drums",
    "dryer",
    "duck",
    "dump",
    "dunk",
    "dust",
    "ear",
    "eat",
    "ebony",
    "elbow",
    "electricity",
    "elephant",
    "elevator",
    "elf",
    "engine",
    "england",
    "escalator",
    "europe",
    "evolution",
    "extension",
    "eyebrow",
    "fan",
    "fancy",
    "fast",
    "feast",
    "fence",
    "fiddle",
    "figment",
    "finger",
    "fire",
    "first",
    "fishing",
    "fix",
    "fizz",
    "flagpole",
    "flannel",
    "flashlight",
    "flock",
    "flower",
    "flu",
    "flush",
    "flutter",
    "fog",
    "foil",
    "football",
    "forehead",
    "forever",
    "fortnight",
    "france",
    "freckle",
    "fringe",
    "frog",
    "frown",
    "gallop",
    "game",
    "garbage",
    "garden",
    "gasoline",
    "gem",
    "ginger",
    "gingerbread",
    "girl",
    "glasses",
    "goblin",
    "gold",
    "goodbye",
    "grandpa",
    "grape",
    "grass",
    "gratitude",
    "gray",
    "green",
    "guitar",
    "gum",
    "gumball",
    "hair",
    "half",
    "handle",
    "handwriting",
    "hang",
    "happy",
    "hat",
    "hatch",
    "headache",
    "heart",
    "hedge",
    "helicopter",
    "hem",
    "hide",
    "hill",
    "hockey",
    "homework",
    "honk",
    "hopscotch",
    "horse",
    "hose",
    "hot",
    "house",
    "houseboat",
    "hug",
    "humidifier",
    "hungry",
    "hurdle",
    "hurt",
    "hut",
    "ice",
    "inn",
    "intern",
    "internet",
    "invitation",
    "ivory",
    "ivy",
    "jade",
    "japan",
    "jeans",
    "jelly",
    "jet",
    "jig",
    "jog",
    "journal",
    "jump",
    "key",
    "killer",
    "kilogram",
    "king",
    "kitchen",
    "kite",
    "knee",
    "kneel",
    "knife",
    "knight",
    "koala",
    "lace",
    "ladder",
    "ladybug",
    "lag",
    "landfill",
    "lap",
    "laugh",
    "laundry",
    "law",
    "lawn",
    "lawnmower",
    "leak",
    "leg",
    "letter",
    "level",
    "lifestyle",
    "light",
    "lightsaber",
    "lime",
    "lion",
    "lizard",
    "log",
    "lollipop",
    "loveseat",
    "loyalty",
    "lunch",
    "lunchbox",
    "lyrics",
    "machine",
    "macho",
    "mailbox",
    "mammoth",
    "mark",
    "mars",
    "mascot",
    "mast",
    "matchstick",
    "mate",
    "mattress",
    "mess",
    "mexico",
    "midsummer",
    "mine",
    "mistake",
    "modern",
    "mold",
    "mom",
    "monday",
    "money",
    "monitor",
    "monster",
    "moon",
    "mop",
    "moth",
    "motorcycle",
    "mountain",
    "mouse",
    "mower",
    "mud",
    "music",
    "mute",
    "nature",
    "negotiate",
    "neighbor",
    "nest",
    "neutron",
    "niece",
    "night",
    "nightmare",
    "nose",
    "oar",
    "observatory",
    "office",
    "oil",
    "old",
    "olympian",
    "opaque",
    "opener",
    "orbit",
    "organ",
    "organize",
    "outer",
    "outside",
    "pail",
    "paint",
    "pajamas",
    "palace",
    "pants",
    "paper",
    "park",
    "parody",
    "party",
    "password",
    "pastry",
    "pawn",
    "pear",
    "pen",
    "pencil",
    "pendulum",
    "penny",
    "pepper",
    "personal",
    "philosopher",
    "phone",
    "photograph",
    "piano",
    "picnic",
    "pigpen",
    "pillow",
    "pilot",
    "pinch",
    "ping",
    "pinwheel",
    "pirate",
    "plaid",
    "plan",
    "plank",
    "plate",
    "platypus",
    "playground",
    "plow",
    "plumber",
    "pocket",
    "poem",
    "point",
    "pole",
    "pool",
    "popsicle",
    "population",
    "portfolio",
    "positive",
    "post",
    "princess",
    "procrastinate",
    "psychologist",
    "publisher",
    "punk",
    "puppet",
    "puppy",
    "push",
    "puzzle",
    "quarantine",
    "queen",
    "quicksand",
    "quiet",
    "race",
    "radio",
    "raft",
    "rag",
    "rainbow",
    "rainwater",
    "random",
    "ray",
    "recycle",
    "red",
    "regret",
    "reimbursement",
    "retaliate",
    "rib",
    "riddle",
    "rim",
    "rink",
    "roller",
    "room",
    "rose",
    "round",
    "roundabout",
    "rung",
    "runt",
    "rut",
    "sad",
    "safe",
    "salmon",
    "salt",
    "sandbox",
    "sandcastle",
    "sandwich",
    "satellite",
    "scar",
    "scared",
    "school",
    "scramble",
    "seashell",
    "season",
    "sentence",
    "sequins",
    "set",
    "shaft",
    "shallow",
    "shampoo",
    "shark",
    "sheep",
    "sheets",
    "sheriff",
    "shipwreck",
    "shirt",
    "shoelace",
    "short",
    "shower",
    "shrink",
    "sick",
    "siesta",
    "silhouette",
    "singer",
    "sip",
    "skate",
    "ski",
    "slam",
    "sleep",
    "sling",
    "slow",
    "slump",
    "sneeze",
    "snow",
    "snuggle",
    "song",
    "space",
    "spare",
    "speakers",
    "spider",
    "spit",
    "sponge",
    "spool",
    "spoon",
    "spring",
    "sprinkler",
    "spy",
    "square",
    "squint",
    "stairs",
    "standing",
    "star",
    "state",
    "stick",
    "stockholder",
    "stoplight",
    "stout",
    "stove",
    "stowaway",
    "straw",
    "stream",
    "streamline",
    "stripe",
    "student",
    "sun",
    "sunburn",
    "sushi",
    "swamp",
    "swarm",
    "sweater",
    "swimming",
    "swing",
    "talk",
    "taxi",
    "teacher",
    "teapot",
    "teenager",
    "telephone",
    "ten",
    "tennis",
    "thief",
    "think",
    "throne",
    "through",
    "thunder",
    "tide",
    "tiger",
    "time",
    "tinting",
    "tiptoe",
    "tiptop",
    "tired",
    "tissue",
    "toast",
    "toilet",
    "tool",
    "toothbrush",
    "tornado",
    "tournament",
    "tractor",
    "train",
    "trash",
    "treasure",
    "tree",
    "triangle",
    "trip",
    "truck",
    "tub",
    "tuba",
    "tutor",
    "television",
    "twang",
    "twig",
    "type",
    "unemployed",
    "upgrade",
    "vest",
    "vision",
    "wag",
    "water",
    "watermelon",
    "wax",
    "wedding",
    "weed",
    "wheelchair",
    "whiplash",
    "whisk",
    "whistle",
    "white",
    "wig",
    "will",
    "windmill",
    "winter",
    "wish",
    "wolf",
    "wool",
    "world",
    "worm",
    "wristwatch",
    "yardstick",
    "zen",
    "zero",
    "zipper",
    "zone",
    "zoo",
]

// Given a seedStr (seed that is a string), generate a list of words
// from the master list.
// numWords is optional, default is 25.
// allWords is an optional list of words to choose from.
function genWords(seedStr, numWords, allWords) {
    numWords = numWords || 25;
    allWords = allWords || wordList;
    // From a seedNum (a number to use as a seed), generate one number between
    // min and max.
    function genOne(seedNum, min, max) {
        min = min || 0;
        max = max || 1;

        seedNum = (seedNum * 9301 + 49297) % 233280;
        var rnd = seedNum / 233280;

        return min + rnd * (max - min);
    }
    function stringToNumber(s) {
        totalNum = "";
        for (var i = 0; i < s.length; i++) {
            totalNum += s.charCodeAt(i);
        }
        return parseInt(totalNum);
    }
    var wordsToReturn = [];

    var start = stringToNumber(seedStr);

    for (var i = 0; i < numWords; i++) {
        var curSeed = start + i;
        var wordIndex = Math.floor(genOne(curSeed, 0, allWords.length - 1));
        wordsToReturn.push(allWords[wordIndex]);
    }
    return wordsToReturn;
}

// Generate a random seedString.
// For now, this is guaranteed to be a string of 3 lowercase alphabet letters.
function genSeedString() {
    var seedStr = "";

    var letters = "abcdefghijklmnopqrstuvwxyz";
    for (var i = 0; i < 3; i++) {
        seedStr += letters.charAt(Math.floor(Math.random() * letters.length));
    }
    return seedStr;
}

// Usually, the board is 5x5 and each cell belongs to either teamA, teamB,
// neutral, or bomb (instant death).
var cellOwner = {
    TEAM_A: "teamA",
    TEAM_B: "teamB",
    NEUTRAL: "neutral",
    BOMB: "bomb",
    UNKNOWN: "unknown",
};

var teams = [cellOwner.TEAM_A, cellOwner.TEAM_B];
function getFirstTeam() {
    return teams[Math.floor(Math.random() * teams.length)];
}
function getOtherTeam(team) {
    if (team === teams[0]) {
        return teams[1];
    }
    return teams[0];
}

// Generate a random boardConfiguration.
// firstTeam is optional, but determines which team goes first.
function genBoardOwners(firstTeam) {
    var firstTeam = firstTeam || getFirstTeam();
    var secondTeam = getOtherTeam(firstTeam);
    // Team that goes first always has 9, second team always has 8.
    var numToAllocate = {
        firstTeam: 9,
        secondTeam: 8,
    };
    numToAllocate[cellOwner.BOMB] = 1;
    numToAllocate[cellOwner.NEUTRAL] = 7;
    var cells = [];
    _.each(numToAllocate, function(allocations, owner) {
        for (var i = 0; i < allocations; i++) {
            cells.push(owner);
        }
    });
    return _.shuffle(cells);
}
